filebeat.inputs:
- type: log
  enabled: true
  fields:
    source: 'ugc'
  paths:
    - /var/log/nginx/*
  json:
    keys_under_root: true
    add_error_key: true

output.logstash:
  enabled: true
  hosts: ["logstash-elk:5045"]